# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76eb48eb6db85ee0a4c808570163f7ec59e977549ebc62ec131a44ae38bf5ee6beb5b8b9ce6322944c145cebcb80d88a16ecaa60a3fe3df77ac8f52688bdd3dd

test:
  secret_key_base: 6a86787d429513c2f73d7168dd2ee8186ac23ca43342bb4fd84f71c4d9cc32a6d18854f6cbb8dcb6f96612a7b125fa681fae35ac26cf1a5d9b17e172c27d818b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
